name: Playwright Tests (UI & API) 

# Run during changes in MAIN branch & schedule run during night (11PM PH-Time)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *' 
jobs:
  test-heroku:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Create .env file
      run: echo "${{ secrets.DOTENV_FILE_CONTENT }}" > .env
      shell: bash

    - name: Cache Node modules
      id: node-cache
      continue-on-error: true
      uses: actions/cache@v5
      with:
        path: |
          ~/.npm
          node_modules
          ~/.cache/
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run run-heroku-chrome-on-linux

    - name: Check output folders
      run: ls -R 
    - uses: actions/upload-artifact@v6
      if: ${{ !cancelled() }}
      with:
        name: heroku-tests-results
        path: reports-cuevaschris-heroku/heroku-tests-chrome-runs
        retention-days: 30

  test-swaglabs:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Create .env file
      run: echo "${{ secrets.DOTENV_FILE_CONTENT }}" > .env
      shell: bash

    - name: Cache Node modules
      id: node-cache
      continue-on-error: true
      uses: actions/cache@v5
      with:
        path: |
          ~/.npm
          node_modules
          ~/.cache/
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run run-swaglabs-tests-on-linux

    - name: Check output folders
      run: ls -R 
    - uses: actions/upload-artifact@v6
      if: ${{ !cancelled() }}
      with:
        name: swaglabs-tests-results
        path: reports-cuevaschris-swaglabs/swaglabs-tests-runs
        retention-days: 30

  api-testing-eviltester-site:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Create .env file
      run: echo "${{ secrets.DOTENV_FILE_CONTENT }}" > .env
      shell: bash

    - name: Cache Node modules
      id: node-cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.npm
          node_modules
          ~/.cache/
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run run-api-testing-on-linux

    - name: Check output folders
      run: ls -R 
    - uses: actions/upload-artifact@v6
      if: ${{ !cancelled() }}
      with:
        name: api-tests-results
        path: reports-cuevaschris-api/api-tests-all-runs
        retention-days: 30